package com.foodlab.common.constant;

public interface AuditConstants {

    String AUDIT_TYPE_FIRST = "FIRST";
    String AUDIT_TYPE_SECOND = "SECOND";

    String AUDIT_STATUS_PENDING = "PENDING";
    String AUDIT_STATUS_PASS = "PASS";
    String AUDIT_STATUS_REJECT = "REJECT";
    String AUDIT_STATUS_RETEST = "RETEST";

    String AUDIT_RESULT_PASS = "PASS";
    String AUDIT_RESULT_FAIL = "FAIL";
    String AUDIT_RESULT_RETEST = "RETEST";

    String ACTION_TYPE_APPROVE = "APPROVE";
    String ACTION_TYPE_REJECT = "REJECT";
    String ACTION_TYPE_RETEST = "RETEST";

    String RETEST_STATUS_PENDING = "PENDING";
    String RETEST_STATUS_DETECTING = "DETECTING";
    String RETEST_STATUS_COMPLETED = "COMPLETED";
    String RETEST_STATUS_ADOPTED = "ADOPTED";

    String ADOPTED_ORIGINAL = "ORIGINAL";
    String ADOPTED_RETEST = "RETEST";

    String SAMPLING_REVIEW_RANDOM = "RANDOM";
    String SAMPLING_REVIEW_STATUS_PENDING = "PENDING";
    String SAMPLING_REVIEW_STATUS_PASS = "PASS";
    String SAMPLING_REVIEW_STATUS_REJECT = "REJECT";
}
