package com.foodlab.common.constant;

public interface TaskConstants {

    String TASK_STATUS_PENDING = "PENDING";
    String TASK_STATUS_ASSIGNED = "ASSIGNED";
    String TASK_STATUS_DETECTING = "DETECTING";
    String TASK_STATUS_SUBMITTED = "SUBMITTED";
    String TASK_STATUS_FIRST_AUDIT = "FIRST_AUDIT";
    String TASK_STATUS_SECOND_AUDIT = "SECOND_AUDIT";
    String TASK_STATUS_COMPLETED = "COMPLETED";
    String TASK_STATUS_REJECTED = "REJECTED";

    String TASK_PRIORITY_HIGH = "HIGH";
    String TASK_PRIORITY_MEDIUM = "MEDIUM";
    String TASK_PRIORITY_LOW = "LOW";

    String TASK_TYPE_NORMAL = "NORMAL";
    String TASK_TYPE_URGENT = "URGENT";

    String TASK_STATUS_IN_PROGRESS = "DETECTING";
    String TASK_STATUS_AUDITING = "AUDITING";
    String TASK_STATUS_APPROVED = "APPROVED";
    String TASK_STATUS_RETEST = "RETEST";
    String TASK_STATUS_SAMPLING_REVIEW = "SAMPLING_REVIEW";
}
