package com.foodlab.schedule.constant;

public interface ScheduleConstants {

    String BATCH_NO_PREFIX = "SCH";

    String SCHEDULE_STATUS_SCHEDULED = "SCHEDULED";
    String SCHEDULE_STATUS_IN_PROGRESS = "IN_PROGRESS";
    String SCHEDULE_STATUS_COMPLETED = "COMPLETED";
    String SCHEDULE_STATUS_CANCELLED = "CANCELLED";
    String SCHEDULE_STATUS_ADJUSTED = "ADJUSTED";

    String SCHEDULE_SOURCE_AUTO = "AUTO";
    String SCHEDULE_SOURCE_MANUAL = "MANUAL";

    String ALGORITHM_GREEDY = "GREEDY";
    String ALGORITHM_GENETIC = "GENETIC";

    int PRIORITY_WEIGHT_HIGH = 10;
    int PRIORITY_WEIGHT_MEDIUM = 5;
    int PRIORITY_WEIGHT_LOW = 1;

    int URGENCY_WEIGHT_URGENT = 20;
    int URGENCY_WEIGHT_NORMAL = 0;

    String INSTRUMENT_STATUS_AVAILABLE = "AVAILABLE";
    String INSTRUMENT_STATUS_MAINTENANCE = "MAINTENANCE";
    String INSTRUMENT_STATUS_DISABLED = "DISABLED";

    String CALENDAR_EVENT_OCCUPIED = "OCCUPIED";
    String CALENDAR_EVENT_MAINTENANCE = "MAINTENANCE";
    String CALENDAR_EVENT_RESERVATION = "RESERVATION";
    String CALENDAR_EVENT_UNAVAILABLE = "UNAVAILABLE";

    String LEAVE_STATUS_PENDING = "PENDING";
    String LEAVE_STATUS_APPROVED = "APPROVED";
    String LEAVE_STATUS_REJECTED = "REJECTED";
    String LEAVE_STATUS_CANCELLED = "CANCELLED";

    String LEAVE_TYPE_ANNUAL = "ANNUAL";
    String LEAVE_TYPE_SICK = "SICK";
    String LEAVE_TYPE_PERSONAL = "PERSONAL";

    String OPERATION_TYPE_GENERATE = "GENERATE";
    String OPERATION_TYPE_ADJUST = "ADJUST";
    String OPERATION_TYPE_CANCEL = "CANCEL";
    String OPERATION_TYPE_PUBLISH = "PUBLISH";
}
